# Generated by Django 5.2.4 on 2025-07-25 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('area', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Площадь')),
                ('rooms', models.SmallIntegerField(verbose_name='Количество комнат')),
                ('mail_cover', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Обложка')),
                ('geo', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('description', models.TextField(verbose_name='Описание')),
                ('promo_video', models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='Видеоролик')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_popular', models.BooleanField(default=False)),
                ('is_new', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Недвижимость',
                'verbose_name_plural': 'Недвижимости',
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Ф.И.О.')),
                ('number', models.PositiveSmallIntegerField(verbose_name='Номер карты')),
                ('cvv', models.PositiveSmallIntegerField(verbose_name='CVV')),
                ('expire_date', models.DateField(verbose_name='Годен до')),
            ],
            options={
                'verbose_name': 'Карта',
                'verbose_name_plural': 'Карты',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('cover', models.ImageField(upload_to='category_covers/', verbose_name='Обложка категории')),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.category', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.city', verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Район',
                'verbose_name_plural': 'Районы',
            },
        ),
        migrations.CreateModel(
            name='ApartmentRent',
            fields=[
                ('estate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product.estate')),
                ('rental_period', models.CharField(max_length=20, verbose_name='Срок аренды')),
            ],
            options={
                'verbose_name': 'Квартира в аренду',
                'verbose_name_plural': 'Квартиры в аренду',
            },
            bases=('product.estate',),
        ),
        migrations.CreateModel(
            name='ApartmentSale',
            fields=[
                ('estate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product.estate')),
                ('floor', models.SmallIntegerField(verbose_name='Этаж')),
                ('total_floors', models.IntegerField(verbose_name='Этажей в доме')),
            ],
            options={
                'verbose_name': 'Квартира на продажу',
                'verbose_name_plural': 'Квартиры на продажу',
            },
            bases=('product.estate',),
        ),
        migrations.CreateModel(
            name='CommercialProperties',
            fields=[
                ('estate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product.estate')),
                ('equipment', models.CharField(max_length=100, verbose_name='Оборудование')),
                ('utilities', models.CharField(max_length=100, verbose_name='Коммуникации')),
            ],
            options={
                'verbose_name': 'Коммерческое помещение',
                'verbose_name_plural': 'Коммерческие помещения',
            },
            bases=('product.estate',),
        ),
        migrations.CreateModel(
            name='GarageforSaleOrRent',
            fields=[
                ('estate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product.estate')),
                ('building_material', models.CharField(max_length=100, verbose_name='Материал постройки')),
            ],
            options={
                'verbose_name': 'Гараж',
                'verbose_name_plural': 'Гаражи',
            },
            bases=('product.estate',),
        ),
        migrations.CreateModel(
            name='HouseSale',
            fields=[
                ('estate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product.estate')),
                ('plot_size', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Площадь участка')),
                ('floors', models.IntegerField(verbose_name='Количество этажей')),
                ('garage', models.BooleanField(default=False, verbose_name='Гараж')),
            ],
            options={
                'verbose_name': 'Дом на продажу',
                'verbose_name_plural': 'Дома на продажу',
            },
            bases=('product.estate',),
        ),
        migrations.AddField(
            model_name='estate',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='estate',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.city', verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='estate',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.district', verbose_name='Район'),
        ),
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.estate', verbose_name='Объект')),
            ],
            options={
                'verbose_name': 'Избранный',
                'verbose_name_plural': 'Избранные',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(verbose_name='Рейтинг')),
                ('comment', models.TextField(verbose_name='Комментарии')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.estate', verbose_name='Объект')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='FeedbackResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Комментарии')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Было создано')),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.feedback', verbose_name='Отзыв')),
            ],
            options={
                'verbose_name': 'Ответ на обратную связь',
                'verbose_name_plural': 'Ответы на обратную связь',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('is_main', models.BooleanField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.estate')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
        migrations.CreateModel(
            name='PaymentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.card', verbose_name='Карта')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.estate')),
            ],
            options={
                'verbose_name': 'Платёжное поручение',
                'verbose_name_plural': 'Платёжные поручения',
            },
        ),
    ]
