# Generated by Django 5.2.4 on 2025-07-29 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_card_user_estate_user_favourite_user_feedback_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favourite',
            old_name='product',
            new_name='estate',
        ),
    ]
