# Generated by Django 5.2.4 on 2025-07-29 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_product_favourite_estate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='product',
            new_name='estate',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='product',
            new_name='estate',
        ),
        migrations.RenameField(
            model_name='paymentorder',
            old_name='product',
            new_name='estate',
        ),
    ]
