# Generated by Django 5.2.4 on 2025-07-30 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_feedback_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackresponse',
            name='feedback',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='product.feedback', verbose_name='Отзыв'),
        ),
    ]
