# Generated by Django 5.2.4 on 2025-07-31 12:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_myuser_is_2fa_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 7, 31, 12, 55, 14, 69142, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
